### ISSUE TITLE
Data Analysis

### ISSUE THREAD

**Issue by joshuaSamuel06** [MIT-Emerging-Talent/2024-group-07-cdsp#24]
I plotted the the data for resident and citizen status emigrants on the world map and also plotted a graph showing the relationship between GDP of the origin countries and number of emigrants from those countries from 2014-2019. Also deleted the unwanted dataset copies.

**Comment by KhalidOmer** [comment]
Maybe change the plot into a bubble plot, the plot of the Gdp and the number of emigrants

**Comment by joshuaSamuel06** [comment]
I have updated the code. Added a scatterplot with bubbles.

**Comment by KhalidOmer** [comment]
Missing country names.
